language:
    - python3
python:
    - "3.5"
    - "3.6"   # current default Python on Travis CI
    - "3.7"
    - "3.8"
before_install:
    - python --version
    - pip install -U pip
    - pip install codecov
    - pip install Werkzeug
    - pip install coverage
    - pip install Flask-Script
    - pip install Flask-Testing
    - pip install selenium
install:
    # Install remaining dev requirements
    - pip install -r dev_requirements.txt
    - pip install -U pytest
script:
    - cd shopyo
    - echo 'Running Tests....'
    - python -m pytest -v
    - sphinx-build -b html sphinx_source docs
after_success:
    - codecov   # submit coverage
